// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:compat/old_cw_core/node.dart';
import 'package:compat/old_cw_core/wallet_info.dart';
import 'package:compat/old_cw_core/wallet_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NodeAdapter());
    registerAdapter(WalletInfoAdapter());
    registerAdapter(WalletTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NodeAdapter());
    registerAdapter(WalletInfoAdapter());
    registerAdapter(WalletTypeAdapter());
  }
}
